apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: void-tls
  namespace: relaypoint
spec:
  dnsNames:
    - void.cs.odu.edu
  issuerRef:
    kind: ClusterIssuer
    name: cs-dns-cluster
  secretName: void-tls