apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: void-postgresql
  namespace: monitoring
spec:
  instances: 3
  storage:
    size: 5Gi
  bootstrap:
    initdb:
      database: void
      owner: void