apiVersion: v1
kind: Service
metadata:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "sticky-session"
    traefik.ingress.kubernetes.io/service.sticky.cookie.secure: "true"
  labels:
    app: void
  name: void
  namespace: monitoring
spec:
  ports:
    - name: website
      port: 3000
  selector:
    app: void
