apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: void-postgres-pvc
  namespace: monitoring
  labels:
    app: void-postgres
    recurring-job.longhorn.io/source: enabled
    recurring-job.longhorn.io/recurring-snapshot: enabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
