apiVersion: v1
kind: Service
metadata:
  labels:
    app: void-postgres
  name: void-postgres
  namespace: monitoring
spec:
  ports:
    - name: postgresql
      port: 5432
  selector:
    app: void-postgres
